name: main

on:
  push:
    branches: [main]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Tag new version
        uses: salsify/action-detect-and-tag-new-version@v2
        with:
          version-command: cat VERSION
